apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recsys.fullname" . }}-api
  labels:
    {{- include "recsys.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.api.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
