{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "recsys.fullname" . }}-minio
  labels:
    {{- include "recsys.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.minio.service.port }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.minio.service.consolePort }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    app.kubernetes.io/name: {{ include "recsys.name" . }}
    app.kubernetes.io/component: minio
{{- end }}
