services:
  api:
    environment:
      GOWORK: /app/go.work.container
    volumes:
      - ${API_TOOLKIT_PATH:-../api-toolkit}:/api-toolkit
      - ${API_SVC_PATH:-../api-svc}:/api-svc

  test:
    environment:
      GOWORK: /app/go.work.container
    volumes:
      - ${API_TOOLKIT_PATH:-../api-toolkit}:/api-toolkit
      - ${API_SVC_PATH:-../api-svc}:/api-svc
