name: reuse-lint

on:
  pull_request:
    paths:
      - "**"
      - ".github/workflows/reuse.yml"
  push:
    branches: [main]

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Install reuse
        run: |
          python -m pip install --upgrade pip
          python -m pip install reuse

      - name: REUSE lint
        run: reuse lint
